// Spark_Vault_uniapp/tests/test_editor_surface.mjs
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const editor = fs.readFileSync(path.join(root, 'src/pages/library/editor.vue'), 'utf8')
const library = fs.readFileSync(path.join(root, 'src/pages/library/index.vue'), 'utf8')
const editorBlock = fs.readFileSync(path.join(root, 'src/components/editor/EditorBlock.vue'), 'utf8')

assert.equal(editor.includes('Document Canvas'), false)
assert.equal(editor.includes('current-subtype-chip'), false)
assert.equal(editor.includes('<EditorToolbar'), false)
assert.equal(editor.includes('tag-strip'), false)
assert.equal(editor.includes('brand-mark'), false)
assert.equal(editor.includes('brand-title'), false)
assert.equal(editor.includes('position: fixed'), true)
assert.equal(editor.includes('meta-card'), true)
assert.equal(editor.includes('writing-paper'), true)
assert.equal(editor.includes('paper-actions'), true)
assert.equal(editor.includes('insert-row'), true)
assert.equal(editor.includes('editor-tags'), true)
assert.equal(editor.includes('lineHeightMode'), true)
assert.equal(editor.includes('quick-entry-page'), true)
assert.equal(editor.includes('quick-sheet'), true)
assert.equal(editor.includes('quick-send'), true)
assert.equal(editor.includes('插件抓取'), false)
assert.equal(editor.includes('mirrorme_open_quick_composer'), true)
assert.equal(editor.includes("uni.switchTab({ url: '/pages/library/index' })"), false)
assert.equal(editor.includes("uni.switchTab({ url: '/pages/home/index' })"), true)

assert.equal(editor.includes("type: 'ordered_list'"), true)
assert.equal(editor.includes("type: 'bullet_list'"), true)
assert.equal(editor.includes("'line_height'"), true)
assert.equal(editor.includes("handleEditorAction('audio')"), true)
assert.equal(editor.includes("handleEditorAction('file')"), true)
assert.equal(editor.includes('+ 标签'), true)

assert.equal(editorBlock.includes('ListBlock'), true)
assert.equal(editorBlock.includes("block.type === 'ordered_list'"), true)

assert.equal(library.includes('quickComposerOpen'), true)
assert.equal(library.includes('composerExpanded'), true)
assert.equal(library.includes('startComposerDrag'), true)
assert.equal(library.includes('endComposerDrag'), true)
assert.equal(library.includes('toggleComposerHeight'), true)
assert.equal(library.includes('resetQuickComposer'), true)
assert.equal(library.includes('setNativeTabBarVisible(false)'), true)
assert.equal(library.includes('setNativeTabBarVisible(true)'), true)
assert.equal(library.includes('this.saveQuick()'), true)
assert.equal(library.includes('addComposerMouseListeners'), true)
assert.equal(library.includes("@mousedown.stop.prevent=\"startComposerDrag\""), true)
assert.equal(library.includes('z-index: 99999'), true)
assert.equal(library.includes('overflow: hidden'), true)
assert.equal(library.includes('min-width: 0'), true)
assert.equal(library.includes('NEW CARD'), false)
assert.equal(library.includes('建一张卡'), false)
assert.equal(library.includes('consumeQuickComposerFlag'), true)
assert.equal(library.includes('mirrorme_open_quick_composer'), true)
assert.equal(library.includes('quick-composer'), true)
assert.equal(library.includes('composer-input'), true)
assert.equal(library.includes('toggleQuickRecord'), true)
assert.equal(library.includes('pickQuickImage'), true)
assert.equal(library.includes('@iconify/vue'), true)
assert.equal(library.includes('lucide:hash'), true)
assert.equal(library.includes('lucide:image'), true)
assert.equal(library.includes('lucide:list-ordered'), true)
assert.equal(library.includes('lucide:mic'), true)
assert.equal(library.includes('showPluginHint'), true)

console.log('editor surface tests passed')
